// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyC0Rs9-W9dWDb7UcZFf_BhV9wiv5g0B6pA',
//     appId: '1:32245459935:web:30fff3ecb06949bed5f26a',
//     messagingSenderId: '32245459935',
//     projectId: 'anetv-f7dd9',
//     authDomain: 'anetv-f7dd9.firebaseapp.com',
//     storageBucket: 'anetv-f7dd9.firebasestorage.app',
//     measurementId: 'G-XL8LBBJPNH',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCTDBe798WtmK5FWwFsQkxYwKGMzkytpzQ',
//     appId: '1:32245459935:android:a05b52c56f77a4e6d5f26a',
//     messagingSenderId: '32245459935',
//     projectId: 'anetv-f7dd9',
//     storageBucket: 'anetv-f7dd9.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAuihMzM-NXf7BoGjQnRUq-rdbexrAwJrM',
//     appId: '1:32245459935:ios:3b7620380d5b9f2dd5f26a',
//     messagingSenderId: '32245459935',
//     projectId: 'anetv-f7dd9',
//     storageBucket: 'anetv-f7dd9.firebasestorage.app',
//     iosBundleId: 'com.example.app',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAuihMzM-NXf7BoGjQnRUq-rdbexrAwJrM',
//     appId: '1:32245459935:ios:3b7620380d5b9f2dd5f26a',
//     messagingSenderId: '32245459935',
//     projectId: 'anetv-f7dd9',
//     storageBucket: 'anetv-f7dd9.firebasestorage.app',
//     iosBundleId: 'com.example.app',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyC0Rs9-W9dWDb7UcZFf_BhV9wiv5g0B6pA',
//     appId: '1:32245459935:web:9f846a8a9865f766d5f26a',
//     messagingSenderId: '32245459935',
//     projectId: 'anetv-f7dd9',
//     authDomain: 'anetv-f7dd9.firebaseapp.com',
//     storageBucket: 'anetv-f7dd9.firebasestorage.app',
//     measurementId: 'G-H7523HG682',
//   );
// }
